
GET http://localhost:3000/user-api/users

###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id" : 200,
    "name" : "Shobu",
    "age" : 20
}

###
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id" : 200,
    "name" : "ArjunReddy",
    "age" : 20
}

### Read a user by id
GET http://localhost:3000/user-api/users/100


###
DELETE http://localhost:3000/user-api/users/id

//For Products
###
GET http://localhost:3000/product-api/products


###
GET http://localhost:3000/product-api/products-id/200


###
GET http://localhost:3000/product-api/products-brand/Lenovo

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productid" : 300,
    "name" : "Laptop",
    "price" : 10000,
    "brand" : "Lenovo"
}


###
PUT http://localhost:3000/product-api/products/id
Content-Type: application/json

{
    "productid" : 100,
    "name" : "IWatch",
    "price" : 20000,
    "brand" : "Lenovo"
}



###
DELETE http://localhost:3000/product-api/products/id
