
//Read all users
GET http://localhost:4000/user-api/user


###Create User
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
    "username": "arjun",
    "password": "mohan",
    "age": 20
}


###
GET http://localhost:3000/user-api/user/697f469822fa683ec5d421b5

###Update User
PUT http://localhost:4000/user-api/users/697f469822fa683ec5d421b5
Content-Type: application/json

{
    "username": "krishna",
    "password": "mohan",
    "age" : 20
}

###Delete user
DELETE http://localhost:4000/user-api/users/697f469822fa683ec5d421b5





//For Products
###Create Product
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
    "productId" : 500,
    "name" : "Iwatch",
    "price" : 70000
}


### Read all products
GET http://localhost:4000/product-api/product


###Get Products by ID

GET http://localhost:4000/product-api/products/697dd2768f620fd98a4c459a


###Update Product
PUT http://localhost:4000/product-api/products/697dd2b38f620fd98a4c45a4
Content-Type: application/json

{
    "productId" : 500,
    "name" : "AppleWatch",
    "price" : 25000
}




###User Authenticated(Login) req
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username" : "krishna",
    "password" : "mohan"
}



### request for protected route
GET http://localhost:4000/user-api/test
